name: ComfyEditor Tests


on:
  push:
  pull_request:
  workflow_dispatch:
    {}

jobs:
  test:
    name: ComfyEditor Unit Tests
    runs-on: macos-15
    steps:
      - name: Skip tests
        run: echo "Skipping tests for now"
      # - uses: actions/checkout@v3
      #
      # - name: Set up Xcode
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: '16.4'
      #
      # - name: Confirm Xcode Version
      #   run: xcodebuild -version
      #
      # - name: Clean DerivedData (just in case)
      #   run: rm -rf ~/Library/Developer/Xcode/DerivedData
      #
      # - name: Build & test (macOS 15.0)
      #   run: |
      #     xcodebuild test \
      #     -scheme ComfyEditorTests \
      #     -workspace ComfyEditor.xcworkspace \
      #     -destination 'platform=macOS' \
      #     -enableCodeCoverage YES | xcpretty
